// let cal = 2+2;
// console.log(cal);
// let res = (cal + 13);
// console.log(res)
// console.log(res+9);
// if(res<=10){
//     console.log('fail');
// }else{
//     console.log("pass")
// }
// let cartquantity = 0;
// console.log(cartquantity);
// let stu = {
//     name : 'safeer',
//     roll : 123,
//     class : 2 ,
//     ispass : true,
// };
// stu.class = stu.class + 3;
// console.log(stu);
// console.log(stu.name , stu.class);

// let a = 5;
// let b = 9;
// let c = 5;

// if(a===b){
//     console.log("this is ture ");
// }else if(a===c){
//     console.log("this is true");
// }else{
//       console.log("this is false")  
// }
// let sum = 5;
// for(let i=0; i<=)
// let marks = [ 29 , 20, 44, 33,33, 97];
// for(let indx=0; indx<marks.length;indx++){
//     console.log(marks[indx]);
// }

// let city = [ khanewal,vehari ,krchi,pindi,multan]
// for(kabuter of city){
//     console.log(city);
// };

// let city = [ "khanewal","vehari","krchi","multan", ]
// for(let cities of city){
//     console.log(cities);
// }
// let marks = [ 45,67,76,88,33,59]
// let sum = 0;
// for(let val of marks){
//     sum = sum+val;
// }
//  let avg = sum/smarks.lenght;
// console.log(avg);

// let marks = [45, 67, 76, 88, 33, 59];
// let sum = 0;

// for (let val of marks) {
//     sum = sum + val;
// }

// let avg = sum / marks.length;
// console.log(avg);
// function safeer(){
//     console.log("hedhd hhedh  ceududc")
//     console.log("hedhd hhedh  ceududc")
//     console.log("hedhd hhedh  ceududc")
//     console.log("hedhd hhedh  ceududc")
//     console.log("hedhd hhedh  ceududc")

// };

// safeer();
// safeer();
// function sum(a,b){
//     s= a-b;
//     console.log(s);
// }
// // sum(4,2);
// let button = document.getElementById(#ss)
// let h1 = document.querySelector('h1')
// console.dir(h1.innerText);
// h1.innerText = h1.innertext + "apna college";
let divs = document.querySelectorAll(".box")
divs[0].innerText= "safeer";
divs[1].innerText= "safeer";
divs[2].innerText= "safeer";

